# Generated by Django 4.2.29 on 2026-03-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=20, unique=True)),
                ('slug', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.CharField(max_length=60, unique=True)),
                ('home_team', models.CharField(max_length=120)),
                ('away_team', models.CharField(max_length=120)),
                ('kickoff', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='odds.tournament')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='BookmakerOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=40)),
                ('market', models.CharField(choices=[('FT_1X2', 'Full Time 1X2'), ('BTTS', 'Both Teams To Score'), ('OU25', 'Over/Under 2.5'), ('OU15', 'Over/Under 1.5'), ('OU35', 'Over/Under 3.5')], max_length=20)),
                ('source', models.CharField(choices=[('oddspapi', 'OddsPapi'), ('theodds', 'The-Odds-API'), ('manual', 'Manual')], default='oddspapi', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('leg1', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('leg2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('leg3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('leg1_label', models.CharField(default='', max_length=20)),
                ('leg2_label', models.CharField(default='', max_length=20)),
                ('leg3_label', models.CharField(default='', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='odds.fixture')),
            ],
        ),
        migrations.CreateModel(
            name='ArbitrageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20)),
                ('pair_label', models.CharField(max_length=30)),
                ('books', models.JSONField()),
                ('odds', models.JSONField()),
                ('stakes', models.JSONField()),
                ('bankroll', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_pct', models.DecimalField(decimal_places=3, max_digits=8)),
                ('arb_sum', models.DecimalField(decimal_places=4, max_digits=8)),
                ('is_high_odds', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arb_results', to='odds.fixture')),
            ],
            options={
                'ordering': ['-profit_pct'],
            },
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['kickoff'], name='odds_fixtur_kickoff_6ec627_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['status'], name='odds_fixtur_status_93dff7_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmakerodds',
            index=models.Index(fields=['fixture', 'market'], name='odds_bookma_fixture_3176ec_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmakerodds',
            index=models.Index(fields=['bookmaker'], name='odds_bookma_bookmak_4bdbd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmakerodds',
            unique_together={('fixture', 'bookmaker', 'market')},
        ),
        migrations.AddIndex(
            model_name='arbitrageresult',
            index=models.Index(fields=['scanned_at'], name='odds_arbitr_scanned_e525a7_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrageresult',
            index=models.Index(fields=['profit_pct'], name='odds_arbitr_profit__aaf196_idx'),
        ),
    ]
