# Generated by Django 4.2.29 on 2026-06-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmakerodds',
            name='market',
            field=models.CharField(choices=[('FT_1X2', 'Full Time 1X2'), ('H2H', 'Head to Head 2-way'), ('BTTS', 'Both Teams To Score'), ('OU25', 'Over/Under 2.5'), ('OU15', 'Over/Under 1.5'), ('OU35', 'Over/Under 3.5')], max_length=20),
        ),
    ]
