# Generated by Django 4.2.29 on 2026-06-14 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0002_alter_bookmakerodds_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Arbitrage Report', max_length=120)),
                ('sport', models.CharField(blank=True, max_length=40)),
                ('market', models.CharField(blank=True, max_length=20)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bankroll', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('books', models.JSONField(default=list)),
                ('arb_count', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('snapshot', models.JSONField(default=list)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('signature', models.CharField(blank=True, max_length=64)),
                ('pdf_path', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='odds_report_created_f4fe5a_idx'), models.Index(fields=['report_id'], name='odds_report_report__219550_idx')],
            },
        ),
    ]
